### ISSUE TITLE
Move storage options (s3, storage-dir) into a pluggable storage backend system

### ISSUE THREAD

**Issue by kylegibson** [PolicyStat/terrarium#33]

**Comment by littleq0903** [comment]
@kylegibson @winhamwr would you mind I help on this issue and add Google Cloud Storage support?

**Comment by littleq0903** [comment]
I probably need Terrarium recently on our service on Google Cloud Platform.

**Comment by winhamwr** [comment]
Heya Colin,

Great to hear from you and I hope you're doing well. Any plans to make PyCon in Montreal this year?

As far as GCS support, that would be excellent! Just let us know if you need any support or have any questions.

Thanks
-Wes

**Comment by littleq0903** [comment]
I can't go to PyCon this year due to military serving, but I will be free since July 7, so maybe next year: )

ok, I will follow the current pattern of S3 support to provide GCS support, then we could find out how to abstract the storage backend system.

**Comment by winhamwr** [comment]
> so maybe next year

I hope so :)

> follow the current pattern of S3 support to provide GCS support

I think that makes sense. Follows the [refactor rule of three](http://en.wikipedia.org/wiki/Rule_of_three_%28computer_programming%29).

**Comment by littleq0903** [comment]
here's my first stab on Google Cloud Storage support:

https://github.com/littleq0903/terrarium/commit/1ddd9ded9c0421e5e9052ddeb93759ea07a3c466

because the api of gcloud/storage are mostly the same of boto's one, so I follow the code to prototyped this one, now going to work on unit tests.

**Comment by littleq0903** [comment]
from #53 

We can find out few methods required to implement a storage class:

required methods:

- `get_bucket(name)`: need to be implemented
- `upload()`: need to be implemented
- `download()`: need to be implemented

optional methods:

- `get_remote_key()`: optional to be overwritten, it's up to the char limitation of that cloud storage (maybe some platform will take some chars as invalid characters.

We can start proposing this implementation of pluggable storage backend.

**Comment by winhamwr** [comment]
Hi Colin,

That seems like a good API to me. I can think of how I'd use to work with an NFS share or with [swift](http://docs.openstack.org/developer/swift/).

-Wes

**Comment by webmaven** [comment]
Swift support would be interesting to me in my current gig.
