### ISSUE TITLE
Add support for virtualenv 12.0

### ISSUE THREAD

**Issue by tinycogio** [PolicyStat/terrarium#51]
Looks like virtualenv 12.0 was released today, and they removed all the older versions. The dependencies for virtualenv in setup.py needs to be updated accordingly.

**Comment by kylegibson** [comment]
Good call. @winhamwr Do you think we should cut a 1.0.0 before, or after, updating support for recent virtualenv/pip releases? We're fairly far behind.

**Comment by winhamwr** [comment]
I would say we update support and then cut a 1.0. Seems like an excellent impetus to call it 1.0

**Comment by winhamwr** [comment]
Hi Giovanni,

> they removed all the older versions

I don't think I follow what that means. Our [travis build](https://travis-ci.org/PolicyStat/terrarium) runs against each of the versions of virtualenv that we support (1.7.X, 1.8.X and 1.9.X), and those tests are passing. It appears that prior versions are still available via pypi.

We would definitely like to support 1.10, 1.11 and 12.x. They have some backwords incompatible changes, though, so someone will need to put in the effort for support. I haven't yet had a need/desire to upgrade to a newer version of virtualenv, so it hasn't made sense for me, yet. Pull requests are definitely welcome :)

Thanks
-Wes

**Comment by tinycogio** [comment]
Hi,

At the time, our servers could not install virtualenv 1.9.1 (as required by terrarium's setup.py) as it appeared to be missing from pypi. I thought they removed all older versions by using the yolk command to list out all version of the package, but it seems that yolk only shows the current version (or I'm doing something wrong).

I ended up manually updating the requirements.txt file in terrarium to 'virtualenv>=12.0,<13.0' which seems to be working fine for us.

Looks like I am also able to install virtualenv 1.9.1 now so looks like the problem was temporary which is good to know since we also don't require the latest version of virtualenv.

Thanks for getting back to me!

**Comment by kylegibson** [comment]
Terrarium has been updated to explicitly support and test against 15.0.x and 15.1.x in additional to the older versions. Eventually we'll drop explicit support for the older versions.
